app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#app_topic_chat:
#    channel: app/chat
#    handler:
#        callback: 'app.topic.chat' #Относится к getName, а не к имени сервиса