#app_topic_chat:
#    channel: app/channel
#    handler:
#        callback: 'app.topic.chat' #Относится к getName, а не к имени сервисаapp.topic.chat

acme_topic_chat:
    channel: app/chat/{room}/{user_id}
    handler:
        callback: 'app.topic.chat' #related to the getName() of your topic
    requirements:
        room:
            pattern: '[a-z]+' #accept all valid regex, don't put delimiters !
        user_id:
            pattern: '\d+'